.TH "reporter-vzlinux-bugs" 1 "September 2016" "Virtuozzo"
.nh
.ad l

.SH "NAME"
reporter-vzlinux-bugs \- Sends reports to public Virtuozzo issue tracker (https://bugs.openvz.org)\&.

.SH "SYNOPSIS"
reporter-vzlinux-bugs

.SH "DESCRIPTION"
The tool creates a new bug in Virtuozzo bug tracker, archives folder specified by DUMP_DIR environment variable and attaches it to a newly created bug\&.

.SH "SEE ALSO"
vzlinux_bugs_event\&.conf(5)

.SH "COPYRIGHT"
Copyright (c) 2015-2016 Parallels IP Holdings GmbH. All rights reserved.
