.TH "reporter-vz-bugs" 1 "September 2016" "Virtuozzo"
.nh
.ad l

.SH "NAME"
reporter-vz-bugs \- Sends reports to public Virtuozzo issue tracker\&.

.SH "SYNOPSIS"
reporter-vz-bugs

.SH "DESCRIPTION"
The tool reads and processes the problem directory \fBDIR\fP\&, then sends the problem report from it to Virtuozzo technical support\&.

If not specified, \fBDIR\fP defaults to the current directory\&.

.SH "SEE ALSO"
virtuozzo_bugs_event\&.conf(5)

.SH "COPYRIGHT"
Copyright (c) 2015-2016 Parallels IP Holdings GmbH. All rights reserved.
