.TH "vzlinux_bugs_event\&.conf" 5 "September 2020" "Virtuozzo Hybrid Server"
.nh
.ad l

.SH "NAME"
vzlinux_bugs_event.conf \- The configuration file for libreport\&.

.SH "DESCRIPTION"
This configuration file provides crash event handlers that report issues to public Virtuozzo bug tracker\&.

By default\&, this file contains an event handler for the report_VzLinuxBugzilla event

.SH "SEE ALSO"
report_event\&.conf(5)

.SH "COPYRIGHT"
Copyright (c) 2015-2020 Virtuozzo International GmbH. All rights reserved.
