#!/bin/bash
# Copyright (C) 2015-2016 Parallels IP Holdings GmbH
#
# This file is part of OpenVZ libraries. OpenVZ is free software; you can
# redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
# Our contact details: Parallels IP Holdings GmbH, Vordergasse 59, 8200
# Schaffhausen, Switzerland.

response=`curl -D- -u ${VZ_Login}:${VZ_Password} -X POST --data '{"fields": {"project": {"key": "VZL"}, "fixVersions": [{"name": "VzLinux7.1"}], "summary": "Anaconda crash - automated report.", "description": "Anaconda crash has been detected.", "issuetype": {"name": "Bug"}}}' -H "Content-Type: application/json" https://bugs.openvz.org/rest/api/2/issue/| grep '"key":'`
id=`echo $response | cut -f4 -d\"`
echo "Created issue $id ($response)"

tar czf /tmp/anaconda.logs.tgz ${DUMP_DIR}

curl -D- -u  ${VZ_Login}:${VZ_Password} -X POST  -H "X-Atlassian-Token: nocheck" -F "file=@/tmp/anaconda.logs.tgz" https://bugs.openvz.org/rest/api/2/issue/${id}/attachments

exit 0
